CREATE INDEX IF NOT EXISTS idx_website_pages_slug ON website_pages(slug);
CREATE INDEX IF NOT EXISTS idx_website_pages_status ON website_pages(status);
CREATE INDEX IF NOT EXISTS idx_website_pages_slug_status ON website_pages(slug, status);
CREATE INDEX IF NOT EXISTS idx_website_pages_updated_at ON website_pages(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_website_sections_page_id ON website_sections(page_id);
CREATE INDEX IF NOT EXISTS idx_website_sections_page_id_sort ON website_sections(page_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_content_blocks_section_id ON website_content_blocks(section_id);
CREATE INDEX IF NOT EXISTS idx_content_blocks_section_id_sort ON website_content_blocks(section_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_media_library_created_at ON media_library(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_media_library_mime_type ON media_library(mime_type);
CREATE INDEX IF NOT EXISTS idx_media_library_folder ON media_library(folder);
CREATE INDEX IF NOT EXISTS idx_profiles_id ON profiles(id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_email ON profiles(email);
CREATE INDEX IF NOT EXISTS idx_profiles_status ON profiles(status);
CREATE INDEX IF NOT EXISTS idx_donations_donor_id ON donations(donor_id);
CREATE INDEX IF NOT EXISTS idx_donations_status ON donations(status);
CREATE INDEX IF NOT EXISTS idx_donations_created_at ON donations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_donations_donor_status ON donations(donor_id, status);
CREATE INDEX IF NOT EXISTS idx_students_sponsorship_status ON students(sponsorship_status);
CREATE INDEX IF NOT EXISTS idx_students_created_at ON students(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_published ON news(published) WHERE published = true;
CREATE INDEX IF NOT EXISTS idx_news_published_at ON news(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_category ON news(category);
CREATE INDEX IF NOT EXISTS idx_gallery_items_is_published ON gallery_items(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_gallery_items_type ON gallery_items(type);
CREATE INDEX IF NOT EXISTS idx_gallery_items_created_at ON gallery_items(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_versions_entity ON content_versions(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_content_versions_page_id ON website_page_versions(page_id);
CREATE INDEX IF NOT EXISTS idx_content_versions_page_id_version ON website_page_versions(page_id, version_number DESC);
CREATE INDEX IF NOT EXISTS idx_hero_content_is_visible ON hero_content(is_visible) WHERE is_visible = true;
CREATE INDEX IF NOT EXISTS idx_donation_content_is_published ON donation_content(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_sponsorship_content_is_published ON sponsorship_content(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_volunteer_content_is_published ON volunteer_content(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_transparency_content_is_published ON transparency_content(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_footer_content_is_published ON footer_content(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_seo_content_page_slug ON seo_content(page_slug);
CREATE INDEX IF NOT EXISTS idx_page_headers_page_slug ON page_headers(page_slug);
CREATE INDEX IF NOT EXISTS idx_section_content_section_key ON section_content(section_key);
CREATE INDEX IF NOT EXISTS idx_site_images_section ON site_images(section);
CREATE INDEX IF NOT EXISTS idx_section_visibility_section_key ON section_visibility(section_key);
CREATE INDEX IF NOT EXISTS idx_cms_strings_key ON cms_strings(key);
CREATE INDEX IF NOT EXISTS idx_navigation_items_location ON navigation_items(location);
CREATE INDEX IF NOT EXISTS idx_navigation_items_sort ON navigation_items(location, sort_order);
CREATE INDEX IF NOT EXISTS idx_design_settings_is_published ON design_settings(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_design_settings_created_at ON design_settings(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_history_user_id ON login_history(user_id);
CREATE INDEX IF NOT EXISTS idx_login_history_created_at ON login_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(user_id, read);
CREATE INDEX IF NOT EXISTS idx_activities_created_at ON activities(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activities_is_public ON activities(is_public) WHERE is_public = true;
CREATE INDEX IF NOT EXISTS idx_testimonials_is_published ON testimonials(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_testimonials_sort_order ON testimonials(sort_order);
CREATE INDEX IF NOT EXISTS idx_student_stories_is_published ON student_stories(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_faqs_is_published ON faqs(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_faqs_sort_order ON faqs(sort_order);
CREATE INDEX IF NOT EXISTS idx_videos_is_featured ON videos(is_featured) WHERE is_featured = true;
CREATE INDEX IF NOT EXISTS idx_videos_created_at ON videos(created_at DESC);
